version: '3.8'

services:
  bankapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9121:9120"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/bankappdb?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Apple@1112
      - SPRING_MAIL_USERNAME=mohannaik050@gmail.com
      - SPRING_MAIL_PASSWORD=aqyqqnotlpjgwbja
    depends_on:
      - mysql-db
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Apple@1112
      - MYSQL_DATABASE=bankappdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge